server:
  port: 8184

spring:
  jpa:
    open-in-view: false
    show-sql: true
    # Ensure Hibernate doesn't try to create tables itself and conflict with your scripts
    hibernate:
      ddl-auto: none
    # This ensures scripts run AFTER Hibernate initializes (if you have entities)
    defer-datasource-initialization: true

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=customer&binaryTransfer=true&reWriteBatchedInserts=true
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:init-schema.sql
      data-locations: classpath:init-data.sql